const jwt = require('jsonwebtoken');

const SECRET_KEY = process.env.JWT_SECRET || "supersecretkey123";

// JWT auth middleware — verifies the token generated by the Python AI Engine
const auth = async (req, res, next) => {
    const authHeader = req.headers.authorization;

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
        return res.status(401).json({ msg: 'No token, authorization denied' });
    }

    const token = authHeader.split(' ')[1];

    try {
        const decoded = jwt.verify(token, SECRET_KEY);

        // Attach user info to request (from sub claim)
        req.auth = {
            userId: decoded.sub,
            email: decoded.email || 'unknown'
        };

        next();
    } catch (err) {
        console.error('Auth middleware error:', err.message);
        res.status(401).json({ msg: 'Token is not valid' });
    }
};

module.exports = auth;
